Levered positions
Midas-Protocol/contracts pull request #622
Opened 2023-04-26 14:41 UTC by vminkov

## Description

Levered positions

2023-05-16 06:32 UTC, vminkov commented
WMATIC-stMATIC
WMATIC-MATICx
jBRL -> 2BRL https://app.midascapital.xyz/56/pool/1

2023-05-16 07:16 UTC, carlomazzaferro commented
Others to add on BNB chain:

- HAY -> ankrBNB
- WBNB -> stkBNB : https://app.midascapital.xyz/56/pool/11
- stkBNB -> aWBNB-stkBNB : https://app.midascapital.xyz/56/pool/11
- MATICx -> MaticX-bba-wmatic : https://app.midascapital.xyz/137/pool/0

2023-05-31 05:43 UTC, carlomazzaferro requested changes

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/compound/Comptroller.sol
> -    bool isCEther,
Better late than never 😅

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPositionStrategy.sol
> +// TODO upgradeable?
Can't see why not

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/BalancerPoolTokenLiquidator.sol
> +  function redeem(IERC20Upgradeable inputToken, uint256 inputAmount, bytes memory strategyData) external override returns (IERC20Upgradeable outputToken, uint256 outputAmount) {
Are these just linting changes?

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/CEtherLiquidator.sol
>    }
Let's just remove this?

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPosition.sol
> +    uint256 maxTopUpCollateralSwapValueScaled = (maxBorrowValueScaled * 10000) / (10000 + MAX_SLIPPAGE);
Let's go over this logic together

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPositionFactory.sol
> +contract LeveredPositionFactory is ILeveredPositionFactory, SafeOwnableUpgradeable {
We might need a `LeveredPositionRegistry` or rather `LeveredPositionLens` or something like the kind to allow the UI to query the data about supported pairs, existing positions, etc.

Some of the logic is here, but we should split it - happy to take your advice

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +import { XBombSwap } from "../XBombLiquidatorFunder.sol";
Should we just remove the XBomb stuff, and use some other liquidators for testing? That pool is otherwise deprecated (or rather, we need to deprecate and force redemptions)

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +    IRouter solidlyRouter = IRouter(ap.getAddress("chainConfig.chainAddresses.SOLIDLY_SWAP_ROUTER"));
Is this really how we store it in the AP?

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +      poolAddress = 0x8159462d255C1D24915CB51ec361F700174cD994; // Balancer stMATIC Stable Pool
Not terribly happy about these hardcoded pools

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +import { XBombSwap } from "../XBombLiquidatorFunder.sol";
@vminkov

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +      //   TODO strategyData = erc4626LiquidatorData(inputToken, outputToken);
Are we sure we have all of them here? E.g. `GelatoGUNiLiquidator`, `CurveLpTokenLiquidatorNoRegistry`

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +    IRouter solidlyRouter = IRouter(ap.getAddress("chainConfig.chainAddresses.SOLIDLY_SWAP_ROUTER"));
@vminkov

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +    // TODO figure out how to query these pools on-chain
Let's do this

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +    internal
And probably remove this

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPosition.sol
> +    address stablePool = _stableMarket.comptroller();
Maybe I am missing something, but these lev positions _could_ work cross-pools? 

I see the next line's `require`, but curious to hear if that'd even be possible

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPosition.sol
> +    baseCollateral = collateralMarket.balanceOfUnderlyingHypo(address(this));
Do we need a require here? Why do we need this variable

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPosition.sol
> +    // repay FL
How does repayment of FL work?

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/midas/levered/LeveredPosition.sol
> +  function getMinLeverageRatioDiff() public view returns (uint256) {
When / how is this used? What does it actually calculate?

2023-05-31 05:43 UTC, carlomazzaferro commented on contracts/test/LeveredPositionTest.t.sol
> +
I believe we need tests also for delevering, closing and liquidating. Could we add these?

2023-05-31 11:41 UTC, vminkov commented on contracts/midas/levered/LeveredPosition.sol
> +  function getMinLeverageRatioDiff() public view returns (uint256) {
I should fix the fn to be `getMinLeverageRatio`

2023-05-31 11:46 UTC, vminkov commented on contracts/midas/levered/LeveredPositionFactory.sol
> +contract LeveredPositionFactory is ILeveredPositionFactory, SafeOwnableUpgradeable {
maybe we should add to the storage an addresses set  that contains all accounts with an open position

2023-05-31 11:56 UTC, vminkov commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +      poolAddress = 0x8159462d255C1D24915CB51ec361F700174cD994; // Balancer stMATIC Stable Pool
we can add them to the AP in a mapping for the input/output tokens

2023-05-31 15:27 UTC, vminkov commented on contracts/midas/levered/LeveredPositionFactory.sol
> +contract LeveredPositionFactory is ILeveredPositionFactory, SafeOwnableUpgradeable {
added it

2023-06-01 07:10 UTC, vminkov commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +      //   TODO strategyData = erc4626LiquidatorData(inputToken, outputToken);
they are all the same as those in the bot - you can check them against https://github.com/Midas-Protocol/monorepo/blob/e51df93cea8caf527e8e995ca34f766d40d07800/packages/sdk/src/modules/liquidation/redemptionStrategy.ts

2023-06-01 08:03 UTC, vminkov commented on contracts/liquidators/registry/LiquidatorsRegistryExtension.sol
> +    IRouter solidlyRouter = IRouter(ap.getAddress("chainConfig.chainAddresses.SOLIDLY_SWAP_ROUTER"));
we will fix these heavy string ids in another PR

2023-06-01 08:38 UTC, carlomazzaferro approved these changes

2023-06-01 12:35 UTC, carlomazzaferro approved these changes

2023-06-01 16:26 UTC, merged